// Frontend/frameworks/angular/src/app/home/home.component.ts
import {AfterViewInit, Component, OnDestroy} from '@angular/core';
import {getLCP, getFCP, getTTFB, Metric} from 'web-vitals';
import {BenchmarkService} from '@shared/services/benchmark.service';
import {ExcelService} from '@shared/services/excel.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements AfterViewInit, OnDestroy {
  cls!: Metric;
  lcp!: Metric;
  fcp!: Metric;
  ttfb!: Metric;
  pageLoaded = 0;
  pageLoadedList: number[] = [];
  fcpList: number[] = [];
  lcpList: number[] = [];
  clsList: number[] = [];
  ttfbList: number[] = [];

  showAllTimes = false;
  reloadsCount = 0;
  timer!: any;

  constructor(private benchmarkService: BenchmarkService,
              private excelService: ExcelService) {
    this.reloadsCount = +JSON.parse(JSON.stringify(localStorage.getItem('reloadsCounter')));
  }

  ngAfterViewInit(): void {
    getLCP(lcp => {
      this.lcp = lcp;
      const lcpLocalStorage = localStorage.getItem('lcp');
      if (lcpLocalStorage) {
        this.lcpList = this.lcpList.concat(JSON.parse(lcpLocalStorage));
      }
      this.lcpList.push(this.lcp.value);
      localStorage.setItem('lcp', JSON.stringify(this.lcpList));
    });
    getTTFB(ttfb => {
      this.ttfb = ttfb;
      const perfData = ttfb.entries[0];
      this.pageLoaded = perfData.duration;
      const pageLoadedTimeLocalStorage = localStorage.getItem('pageLoaded');
      const ttfbTimeLocalStorage = localStorage.getItem('ttfb');

      if (pageLoadedTimeLocalStorage) {
        this.pageLoadedList = this.pageLoadedList.concat(JSON.parse(pageLoadedTimeLocalStorage));
      }
      if (ttfbTimeLocalStorage) {
        this.ttfbList = this.ttfbList.concat(JSON.parse(ttfbTimeLocalStorage));
      }
      this.pageLoadedList.push(this.pageLoaded);
      this.ttfbList.push(this.ttfb.value);
      localStorage.setItem('pageLoaded', JSON.stringify(this.pageLoadedList));
      localStorage.setItem('ttfb', JSON.stringify(this.ttfbList));
    });
    getFCP(fcp => {
      this.fcp = fcp;
      const fcpLocalStorage = localStorage.getItem('fcp');
      if (fcpLocalStorage) {
        this.fcpList = this.fcpList.concat(JSON.parse(fcpLocalStorage));
      }
      this.fcpList.push(this.fcp.value);
      localStorage.setItem('fcp', JSON.stringify(this.fcpList));
    }, true);
    this.timer = setTimeout(() => this.reload(), 1000);
  }

  runBenchmark(): void {
    this.clearLocalStorage();
    this.reloadsCount = this.benchmarkService.selectedNumberOfBenchmarks;
    this.reload();
  }

  reload(): void {
    if (this.reloadsCount > 0) {
      localStorage.setItem('reloadsCounter', (--this.reloadsCount).toString());
      window.location.reload();
    }
  }

  clearLocalStorage(): void {
    localStorage.clear();
    this.ttfbList = [];
    this.fcpList = [];
    this.lcpList = [];
    this.pageLoadedList = [];
  }

  ngOnDestroy(): void {
    clearTimeout();
  }

  saveExcel(): void {
    const times = [
      {
        title: 'fcp',
        data: this.fcpList
      },
      {
        title: 'lcp',
        data: this.lcpList
      },
      {
        title: 'ttfb',
        data: this.ttfbList,
      },
      {
        title: 'pageLoadingTime',
        data: this.pageLoadedList
      }
    ];

    this.excelService.savePageLoadingToExcel(times, 'PAGE_LOADING_TIMES');
  }
}

  <div class="home-container flex-column flex-center">
    <ul class="loading-metrics-box">
      <li *ngIf="fcp"><b>First Contentful Paint (FCP)</b> | {{ fcp.value | number:'.5-5' }} ms</li>
      <li *ngIf="lcp"><b>Largest Contentful Paint (LCP)</b> | {{ lcp.value | number:'.5-5' }} ms</li>
      <li *ngIf="ttfb"><b>Time To First Byte (TTFB)</b> | {{ ttfb.value | number:'.5-5'}} ms</li>
      <li *ngIf="pageLoaded"><b>Page loading time</b> | {{ pageLoaded | number:'.5-5' }} ms</li>
    </ul>
    <div class="flex-row wrap-times" style="gap: 40px">
      <div>
        <p>First Contentful Paint (FCP)</p>
        <ul class="loading-metrics-box">
          <li *ngFor="let fcpTime of fcpList">
            {{ fcpTime | number:'.5-5' }} ms
          </li>
        </ul>
      </div>
      <div>
        <p>Largest Contentful Paint (LCP)</p>
        <ul class="loading-metrics-box">
          <li *ngFor="let lcpTime of lcpList">
            {{ lcpTime | number:'.5-5' }} ms
          </li>
        </ul>
      </div>
      <div>
        <p>Time To First Byte (TTFB)</p>
        <ul class="loading-metrics-box">
          <li *ngFor="let ttfbTime of ttfbList">
            {{ ttfbTime | number:'.5-5' }} ms
          </li>
        </ul>
      </div>
      <div>
        <p>Page loading time</p>
        <ul class="loading-metrics-box">
          <li *ngFor="let pageLoadingTime of pageLoadedList">
            {{ pageLoadingTime | number:'.5-5' }} ms
          </li>
        </ul>
      </div>
    </div>
    <div class="flex-row" style="gap: 20px; margin-bottom: 25px">
      <button mat-raised-button color="primary" type="button" (click)="runBenchmark()">Run benchmark</button>
      <button mat-raised-button class="red-btn" type="button" (click)="clearLocalStorage()">Clear local storage</button>
      <button mat-raised-button
              type="button"
              (click)="saveExcel()">
        <mat-icon>file_download</mat-icon>Save times to excel
      </button>
    </div>
  </div>

<!--<div class="home-container">-->
<!--  <div class="main-box gradient-right flex-column flex-center">-->
<!--    <h1><b>search</b> for local stores<br>that will deliver <b>your purchases</b></h1>-->
<!--    <div>-->
<!--      <button mat-flat-button type="button" style="margin-right: 10px"-->
<!--              cdkOverlayOrigin #webVitals="cdkOverlayOrigin">-->
<!--        <mat-icon (click)="showAllTimes = !showAllTimes">expand_more</mat-icon>-->
<!--      </button>-->
<!--      <button mat-flat-button type="button" (click)="runBenchmark()">Run benchmark</button>-->
<!--    </div>-->
<!--    <div class="search-form">-->
<!--      <label>-->
<!--        <input type="text" placeholder="search your address" />-->
<!--      </label>-->
<!--      <button type="button" mat-button>search</button>-->
<!--    </div>-->
<!--  </div>-->
<!--  <div class="about-box flex-row flex-space_around-center">-->
<!--    <div class="img-box flex-center">-->
<!--      <img src="assets/images/png/hand.png" alt="hand image">-->
<!--      <p><b>we support</b><br> local stores,<br>by adding new stores</p>-->
<!--    </div>-->
<!--    <div class="img-box flex-center">-->
<!--      <img src="assets/images/png/bag.png" alt="bag image">-->
<!--      <p><b>you also help</b>,<br> by buying locally instead of <br>in chain stores</p>-->
<!--    </div>-->
<!--    <div class="img-box flex-center">-->
<!--      <img src="assets/images/png/open.png" alt="open sign image">-->
<!--      <p><b>enter the address and check</b>,<br> which stores in the area<br> will supply you with shopping</p>-->
<!--    </div>-->
<!--    <div class="img-box flex-center">-->
<!--      <img src="assets/images/png/telephone.png" alt="telephone image">-->
<!--      <p><b>at this point</b><br> you can place an order<br>by calling the store</p>-->
<!--    </div>-->
<!--    <div class="img-box flex-center">-->
<!--      <img src="assets/images/png/laptop.png" alt="laptop image">-->
<!--      <p><b>soon</b><br> online ordering system<br>will be available</p>-->
<!--    </div>-->
<!--  </div>-->
<!--  <div class="divider"></div>-->
<!--  <div class="add-shop-box flex-row flex-center">-->
<!--    <img src="assets/images/png/arrow_right.png" class="margin-right" alt="arrow right image">-->
<!--    <div class="flex-column flex-center">-->
<!--      <h1>if you <b>run your store</b>,<br> you can <b>add it</b> for free to our catalog</h1>-->
<!--      <button mat-raised-button>add shop</button>-->
<!--    </div>-->
<!--    <img src="assets/images/png/arrow_left.png" class="margin-left" alt="arrow left image">-->
<!--  </div>-->
<!--  <div class="soon-ordering-box gradient-left flex-row flex-center">-->
<!--    <div class="ordering-text flex-column">-->
<!--      <h1><b>soon</b><br> you will make and pay<br> for your purchases<br> completely <b>online</b></h1>-->
<!--      <h2>in four simple steps</h2>-->
<!--    </div>-->
<!--    <div class="smartphone-img">-->
<!--      <img src="assets/images/png/smartphone.png" alt="smartphone image">-->
<!--    </div>-->
<!--  </div>-->
<!--  <div class="steps-to-order flex-row flex-space_around-center">-->
<!--    <div class="flex-row flex-center step-img-box">-->
<!--      <img src="assets/images/svg/first.svg" alt="first">-->
<!--      <p><b>enter the address and search</b><br> for local shops in your area</p>-->
<!--    </div>-->
<!--    <div class="flex-row flex-center step-img-box">-->
<!--      <img src="assets/images/svg/second.svg" alt="second">-->
<!--      <p><b>select the store you are<br> interested in</b> that has made available<br> the online shopping option</p>-->
<!--    </div>-->
<!--    <div class="flex-row flex-center step-img-box">-->
<!--      <img src="assets/images/svg/third.svg" alt="third">-->
<!--      <p><b>add products to the cart,</b><br> place the order and wait<br> for confirmation from the store</p>-->
<!--    </div>-->
<!--    <div class="flex-row flex-center step-img-box">-->
<!--      <img src="assets/images/svg/fourth.svg" alt="fourth">-->
<!--      <p><b>when the store confirms</b><br>the availability of all<br> products, pay for the order<br> and wait for delivery</p>-->
<!--    </div>-->
<!--  </div>-->
<!--  <div class="soon-ordering-box gradient-right flex-row flex-center">-->
<!--    <div class="smartphone-img">-->
<!--      <img src="assets/images/png/shoppingBag.png" alt="shopping bag">-->
<!--    </div>-->
<!--    <div class="flex-column flex-center">-->
<!--      <h1><b>why</b> is it worth buying<br> locally with <b>wamtu.pl</b></h1>-->
<!--      <ol>-->
<!--        <li>you support local stores instead of global networks</li>-->
<!--        <li>everything is free, you only pay for purchases</li>-->
<!--        <li>on wamtu.pl, just enter the address, we will search for stores in the area for you</li>-->
<!--        <li>clear and readable system - you will definitely not get lost</li>-->
<!--        <li>safe and comfortable - why stand in line at the checkout when shopping can come to you</li>-->
<!--      </ol>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->

<!--<ng-template-->
<!--  cdkConnectedOverlay-->
<!--  [cdkConnectedOverlayOrigin]="webVitals"-->
<!--  [cdkConnectedOverlayOpen]="showAllTimes"-->
<!--&gt;-->
<!--  <div>-->
<!--    <ul class="dropdown-overlay">-->
<!--      <li *ngIf="cls">{{ cls.name }} | {{ cls.value }} ms</li>-->
<!--      <ul *ngIf="clsList.length > 0">-->
<!--        <li *ngFor="let clsItem of clsList">{{ clsItem }}</li>-->
<!--      </ul>-->
<!--      <li *ngIf="lcp">{{ lcp.name }} | {{ lcp.value }} ms</li>-->
<!--      <li *ngIf="fcp">{{ fcp.name }} | {{ fcp.value }} ms</li>-->
<!--      <li *ngIf="ttfb">{{ ttfb.name }} | {{ ttfb.value }} ms</li>-->
<!--      <li *ngIf="pageLoaded">Page loading time | {{ pageLoaded }}</li>-->
<!--    </ul>-->
<!--  </div>-->

<!--</ng-template>-->

// Frontend/frameworks/reactjs/src/pages/Home/Home.jsx
import React, {Component} from "react";
import "./Home.css"
import { getFCP, getLCP, getTTFB } from 'web-vitals';
import {Button} from "@material-ui/core";
import {DisplayLoadingTimes} from "./components/DisplayLoadingTimes";

const fcpTitle = "First Contentful Paint (FCP)";
const lcpTitle = "Largest Contentful Paint (LCP)";
const ttfbTitle = "Time To First Byte (TTFB)";
const pageLoadingTitle = "Page loading time";

class Home extends Component {
    reloadsCount = 0;
    timer = null;
    constructor(props) {
        super(props);
        this.state = {
            fid: 0,
            fcp: 0,
            lcp: 0,
            ttfb: 0,
            pageLoaded: 0,
            pageLoadedList: [],
            fcpList: [],
            lcpList: [],
            clsList: [],
            ttfbList: []
        }
        this.reloadsCount = +localStorage.getItem("reloadsCounter")
    }

    componentDidMount() {
        getTTFB(ttfb => {
            const perfData = ttfb.entries[0];
            const pageLoaded = perfData.duration;
            let pageLoadedList = JSON.parse(localStorage.getItem("pageLoaded"));
            let ttfbList = JSON.parse(localStorage.getItem("ttfb"));
            if (pageLoadedList === null) {
                pageLoadedList = [];
            }
            if (ttfbList === null) {
                ttfbList = [];
            }
            pageLoadedList.push(pageLoaded);
            ttfbList.push(ttfb.value)
            localStorage.setItem("pageLoaded", JSON.stringify(pageLoadedList));
            localStorage.setItem("ttfb", JSON.stringify(ttfbList));
            this.setState({ttfb, pageLoaded, pageLoadedList, ttfbList});
        });
        getFCP(fcp => {
            let fcpList = JSON.parse(localStorage.getItem("fcp"));
            if (fcpList === null) {
                fcpList = [];
            }
            fcpList.push(fcp.value);
            localStorage.setItem("fcp", JSON.stringify(fcpList));
            this.setState({fcp, fcpList});
        }, true);
        getLCP(lcp => {
            let lcpList = JSON.parse(localStorage.getItem("lcp"));
            if (lcpList === null) {
                lcpList = [];
            }
            lcpList.push(lcp.value);
            localStorage.setItem("lcp", JSON.stringify(lcpList));
            this.setState({lcp, lcpList});
        }, true);
        this.timer = setTimeout(() => this.reload(), 1000);
    }

    componentWillUnmount() {
        clearTimeout(this.timer);
    }

    runBenchmark() {
        this.reloadsCount = 5;
        this.clearLocalStorage();
        this.reload();
    }

    clearLocalStorage() {
        localStorage.clear();
        this.setState({ fcpList: [], lcpList: [], ttfbList: [], pageLoadedList: []});
    }

    reload() {
        if(this.reloadsCount > 0) {
            localStorage.setItem("reloadsCounter", (--this.reloadsCount).toString());
            window.location.reload();
        }
    }

    render() {
        return (
            <div className="Home flex-column">
                <div>
                    <p><b>{fcpTitle}:</b> {this.state.fcp.value} ms</p>
                    <p><b>{lcpTitle}:</b> {this.state.lcp.value} ms</p>
                    <p><b>{ttfbTitle}:</b> {this.state.ttfb.value} ms</p>
                    <p><b>{pageLoadingTitle}:</b> {this.state.pageLoaded } ms</p>
                </div>
                <div className="flex-row flex-center">
                    <DisplayLoadingTimes title={fcpTitle} times={this.state.fcpList}/>
                    <DisplayLoadingTimes title={lcpTitle} times={this.state.lcpList}/>
                    <DisplayLoadingTimes title={ttfbTitle} times={this.state.ttfbList}/>
                    <DisplayLoadingTimes title={pageLoadingTitle} times={this.state.pageLoadedList}/>
                </div>
                <div className="ButtonMargin">
                    <Button variant="contained"
                            color="primary"
                            onClick={() => this.runBenchmark()}>Run benchmark</Button>

                    <Button variant="contained"
                            className="red-btn"
                            onClick={() => this.clearLocalStorage()}>Clear local storage</Button>

                    <Button variant="contained"
                            color="primary"
                            onClick={() => this.runBenchmark()}>Save to excel</Button>
                </div>
            </div>
        )
    }
}

export default Home;
